<MainMenu>:
    FloatLayout:
        Label:
            id: WelcomeLabel
            text: "Welcome on LoRe, the learning system for best students"
            size: 250, None           # Largeur fixe de 300px, hauteur auto
            size_hint: 0.8, None
            text_size: self.width+0, None 
            wrap: True
            size: 300, 75          # Taille du label (200 px par 50 px)
            pos_hint: {"center_x": 0.40, "top": 1}